services:
  postgres:
    container_name: postgres-electronic-store
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: electronic_store
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - electronic-store
    restart: unless-stopped

  keycloak:
    container_name: keycloak-electronic-store
    image: quay.io/keycloak/keycloak:26.1.0
    ports:
      - 3030:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - electronic-store
    command:
      - "start-dev"

networks:
  electronic-store:
    driver: bridge


volumes:
  postgres:
    driver: local